










getDetL(n,aL,DL):=block([k,M],M:genmatrix(lambda([i,j],rand(aL)),n,n),for k while ((k<3000) and not member(determinant(M),DL)) do (M:genmatrix(lambda([i,j],rand(aL)),n,n)),return(M));


getDetLnotE(n,aL,DL):=block([k,M,En],En:genmatrix(lambda([i,j],if i=j then 1 else 0),n,n),M:genmatrix(lambda([i,j],rand(aL)),n,n),for k while ((k<3000) and (not member(determinant(M),DL) or equal(M,En))) do (M:genmatrix(lambda([i,j],rand(aL)),n,n)),return(M));


random_matrix_det_list(n,aL,DL):=getDetLnotE(n,aL,DL);


getRegM(n,aL):=block([k,M],M:genmatrix(lambda([i,j],rand(aL)),n,n),for k while ((k<3000) and equal(determinant(M),0)) do (M:genmatrix(lambda([i,j],rand(aL)),n,n)),return(M));
random_invertible_matrix(n,aL):=getRegM(n,aL);



distMat(A,B):=block([i,j,r,c,dt],dt:0,[r,c]:matrix_size(A),for i:1 while i<=r do (for j:1 while j<=c do (if is(notequal(A[i,j],B[i,j])) then dt:dt+1)),return([dt,r*c]));


chkDiag(m,n):=is(matrix_size(m)=[n,n]) and is(equal(m,genmatrix(lambda([i,j],if i=j then m[i,i] else 0),n,n)));


LtoS(L):=block([s],s:ssubst("(","[",ssubst(")","]",string(L))),return(s));


MtoTeX(M):=block([m,n,i,j,s],s:"\\begin{pmatrix}",[m,n]:matrix_size(M),for i:1 thru m do (for j:1 thru n do (s:sconcat(s,M[i,j]),if j<n then s:sconcat(s,"&")),if i<m then s:sconcat(s,"\\\\")),return(sconcat(s,"\\end{pmatrix}")));

MtoTeX2(M,env):=block([m,n,i,j,s],s:sconcat("\\begin{",env,"}"),[m,n]:matrix_size(M),for i:1 thru m do (for j:1 thru n do (s:sconcat(s,M[i,j]),if j<n then s:sconcat(s,"&")),if i<m then s:sconcat(s,"\\\\")),return(sconcat(s,"\\end{",env,"}")));


CountDf(m1,m2):=block([k,r,c,r1,c1],[r,c]:matrix_size(m1),k:0,for r1:1 thru r do for c1:1 thru c do if not m1[r1,c1]=m2[r1,c1] then k:k+1,return(k));
