出力しました: mcq_template_post.mac
_LANG);
%__Cmsg2:if listp(%__Cmsg2L) then %__mcq_lang(%__Cmsg2L, %_STACK_LANG) else "";
%__Cmsg3:if listp(%__Cmsg3L) then %__mcq_lang(%__Cmsg3L, %_STACK_LANG) else "";
%__Cmsg4:if listp(%__Cmsg4L) then %__mcq_lang(%__Cmsg4L, %_STACK_LANG) else "";
%__Cmsg5:if listp(%__Cmsg5L) then %__mcq_lang(%__Cmsg5L, %_STACK_LANG) else "";
%__Cmsg6:if listp(%__Cmsg6L) then %__mcq_lang(%__Cmsg6L, %_STACK_LANG) else "";
%__Cmsg7:if listp(%__Cmsg7L) then %__mcq_lang(%__Cmsg7L, %_STACK_LANG) else "";
%__Cmsg8:if listp(%__Cmsg8L) then %__mcq_lang(%__Cmsg8L, %_STACK_LANG) else "";
%__Wmsg1:%__mcq_lang(%__Wmsg1L, %_STACK_LANG);
%__Wmsg2:if listp(%__Wmsg2L) then %__mcq_lang(%__Wmsg2L, %_STACK_LANG) else "";
%__Wmsg3:if listp(%__Wmsg3L) then %__mcq_lang(%__Wmsg3L, %_STACK_LANG) else "";
%__Wmsg4:if listp(%__Wmsg4L) then %__mcq_lang(%__Wmsg4L, %_STACK_LANG) else "";
%__Wmsg5:if listp(%__Wmsg5L) then %__mcq_lang(%__Wmsg5L, %_STACK_LANG) else "";
%__Wmsg6:if listp(%__Wmsg6L) then %__mcq_lang(%__Wmsg6L, %_STACK_LANG) else "";
%__Wmsg7:if listp(%__Wmsg7L) then %__mcq_lang(%__Wmsg7L, %_STACK_LANG) else "";
%__Wmsg8:if listp(%__Wmsg8L) then %__mcq_lang(%__Wmsg8L, %_STACK_LANG) else "";
%__Wmsg9:if listp(%__Wmsg9L) then %__mcq_lang(%__Wmsg9L, %_STACK_LANG) else "";
%__mcq_addCopt(%__Copt1, %__Cmsg1);
%__mcq_addCopt(%__Copt2, %__Cmsg2);
%__mcq_addCopt(%__Copt3, %__Cmsg3);
%__mcq_addCopt(%__Copt4, %__Cmsg4);
%__mcq_addCopt(%__Copt5, %__Cmsg5);
%__mcq_addCopt(%__Copt6, %__Cmsg6);
%__mcq_addCopt(%__Copt7, %__Cmsg7);
%__mcq_addCopt(%__Copt8, %__Cmsg8);
%__mcq_addWopt(%__Wopt1, %__Wmsg1);
%__mcq_addWopt(%__Wopt2, %__Wmsg2);
%__mcq_addWopt(%__Wopt3, %__Wmsg3);
%__mcq_addWopt(%__Wopt4, %__Wmsg4);
%__mcq_addWopt(%__Wopt5, %__Wmsg5);
%__mcq_addWopt(%__Wopt6, %__Wmsg6);
%__mcq_addWopt(%__Wopt7, %__Wmsg7);
%__mcq_addWopt(%__Wopt8, %__Wmsg8);
%__mcq_addWopt(%__Wopt9, %__Wmsg9);

%__mcq_max_opts:10; 
%__mcq_max_patterns:99; 


%__mcq_cw_delimiter:%__mcq_max_opts*(%__mcq_max_patterns+1);
%__mcq_CLlen:map(length, %__mcq_CLbase);
%__mcq_WLlen:map(length, %__mcq_WLbase);
%__mcq_nC:%__mcq_min_max(%__mcq_num_copts, length(flatten(%__mcq_CLbase)));
%__mcq_nW:%__mcq_min_max(%__mcq_num_wopts, length(flatten(%__mcq_WLbase)));




%_rp(L):=random_permutation(L);
%__mcq_make_pattern(on, bsL):=block([l:length(bsL), k, ptL:map(length,bsL), pt], if on=0 then return([]) 
else if on>=l then while apply("+",ptL)>on do (k:rand(l)+1, if ptL[k]>1 then ptL[k]:ptL[k]-1) 
else (ptL:makelist(0, l),while apply("+", ptL)<on do (k:rand(l)+1, if ptL[k]=0 then ptL[k]:1)), return(ptL));
%__mcq_nCL:%__mcq_make_pattern(%__mcq_nC, %__mcq_CLbase);
%__mcq_nWL:%__mcq_make_pattern(%__mcq_nW, %__mcq_WLbase);
%__mcq_CLL:makelist(makelist(%__mcq_CLbase[k][j], j, 1, min(%__mcq_nCL[k], length(%__mcq_CLbase[k]))), k, 1, length(%__mcq_nCL));
%__mcq_WLL:makelist(makelist(%__mcq_WLbase[k][j], j, 1, min(%__mcq_nWL[k], length(%__mcq_WLbase[k]))), k, 1, length(%__mcq_nWL));

%__mcq_nocorrect_id:%__mcq_max_patterns+1;
%__mcq_noc_id:%__mcq_nocorrect_id*%__mcq_cw_delimiter;
%__mcq_noidea_flag:%__mcq_max_patterns*10+1;
%__mcq_noi_id:%__mcq_noidea_flag*%__mcq_cw_delimiter;
%__mcq_NCL:if %__mcq_nocorrectopt and %__mcq_nocorrecttrue then [[1, true, %__mcq_nocoptS]] else [[%__mcq_noc_id, false, %__mcq_nocoptS]];

%__mcq_NOI:[[%__mcq_noi_id, false, %__mcq_noidS]];
%__mcq_ListCL0:apply(append, makelist(makelist([%__mcq_max_opts*k+j, true, %__mcq_CLL[k][j]], j, 1, length(%__mcq_CLL[k])), k, 1, length(%__mcq_CLL)));
%__mcq_ListWL0:apply(append, makelist(makelist([%__mcq_cw_delimiter*k+j, false, %__mcq_WLL[k][j]], j, 1, length(%__mcq_WLL[k])), k, 1, length(%__mcq_WLL)));
%__mcq_ListCL1:%_rp(%__mcq_ListCL0);
%__mcq_ListWL1:%_rp(%__mcq_ListWL0);
%__mcq_taC:%_rp(makelist(%__mcq_ListWL1[k], k, 1, %__mcq_num_wopts));
%__mcq_taW:%_rp(append(makelist(%__mcq_ListCL1[k], k, 1, %__mcq_num_copts), makelist(%__mcq_ListWL1[k], k, 1, %__mcq_num_wopts)));
ta1:%__mcq_taW;
if %__mcq_nocorrectopt then (if %__mcq_nocorrecttrue then ta1:append(%__mcq_taC, %__mcq_NCL) else ta1:append(%__mcq_taW, %__mcq_NCL));
if %__mcq_noidea then ta1:append(ta1, %__mcq_NOI);
Cans1:mcq_correct(ta1);

%__mcq_qtext:%__mcq_lang(%__mcq_qtextL, %_STACK_LANG);
%__mcq_SELALLL:[
 ["en", "all correct options"],
 ["ja", "すべて選べ"],
 ["fr", "Tout sélectionner"],
 ["de", "Alle zutreffenden auswählen."],
 ["other", ""]
];
%__mcq_SELALL:%__mcq_lang(%__mcq_SELALLL, %_STACK_LANG);
%__mcq_SELONEANYL:[
 ["en", "Choose one. Even if there are multiple correct answers, select only one."],
 ["ja", "選べ. 正解が2つ以上ある場合も1つ選べばよい."],
 ["fr", "Choisissez une seule réponse. Même s’il y a plusieurs réponses correctes, n’en sélectionnez qu’une."],
 ["de", "Wählen Sie eine Antwort. Auch wenn es mehrere richtige Antworten gibt, wählen Sie nur eine."],
 ["other", ""]
];
%__mcq_SELONEANY:%__mcq_lang(%__mcq_SELONEANYL, %_STACK_LANG);
%__mcq_SELL:[["en", "choose"], ["ja", "選べ"], ["fr", "Choisissez."], ["de", "Wählen Sie."]];
%__mcq_SEL:%__mcq_lang(%__mcq_SELL, %_STACK_LANG);
if %__mcq_rb_cb="cb" then %__mcq_seltype:%__mcq_SELALL else if %__mcq_num_copts>1 then %__mcq_seltype:%__mcq_SELONEANY else %__mcq_seltype:%__mcq_SEL;
if %__mcq_qtext_auto then qtext:ssubst(%__mcq_seltype, "__SELTYPE__", %__mcq_qtext);