









kihonP(n,i1,j1,c):=block([M],M:genmatrix(lambda([i,j],if i=j then 1 elseif equal([i,j],[i1,j1]) then c else 0),n,n),return(M));
kihonQ(n,i1,c):=block([M],M:genmatrix(lambda([i,j],if i=j then (if i=i1 then c else 1) else 0),n,n),return(M));
kihonR(n,i1,j1):=block([M],M:genmatrix(lambda([i,j],if i=j then 1 else 0),n,n),M[i1,i1]:0,M[j1,j1]:0,M[i1,j1]:1,M[j1,i1]:1,return(M));


elementary_matrix_rowadd(n, i, j, c):=kihonP(n, i, j, c);
elementary_matrix_swap(n, i, j):=kihonR(n, i, j);
elementary_matrix_mult(n, i, c):=kihonQ(n, i, c);


sweepout(rc, A, i1, j1):=block([k, M, m, n],
  [m,n]:matrix_size(A), M:A, if rc=1 then (for k:1 while (k<=n)
    do (if not k=j1 then M:M.kihonP(n,j1,k,-M[i1,k]/M[i1,j1])),return(M))
        else (for k:1 while (k<=m) do (if notequal(k,i1) then M:kihonP(m,k,i1,-M[k,j1]/M[i1,j1]).M),return(M)));

SweepCBij(M, i, j):=block([em, k, r, c],
  [r,c]:matrix_size(M), em:genmatrix(lambda([i,j], if i=j then 1 else 0), r, r),
  for k:i+1 thru r do em:kihonP(r, k, i, -M[k,j]/M[i,j]).em, return(em));

SweepCij(M, i, j):=block([em, k, r, c],
  [r,c]:matrix_size(M), em:genmatrix(lambda([i, j], if i=j then 1 else 0), r, r),
  for k:1 thru r do if not k=i then em:kihonP(r, k, i, -M[k,j]/M[i,j]).em, return(em));

SweepRij(M, i, j):=block([em, k, r, c],
  [r,c]:matrix_size(M), em:genmatrix(lambda([i, j], if i=j then 1 else 0), c, c),
  for k:1 thru c do if not k=j then em:em.kihonP(c, j, k, -M[i,k]/M[i,j]), return(em));

SweepRRij(M, i, j):=block([em, k, r, c],
  [r, c]:matrix_size(M), em:genmatrix(lambda([i, j], if i=j then 1 else 0), c, c),
  for k:j+1 thru c do em:em.kihonP(c, j, k, -M[i,k]/M[i,j]), return(em));

SweepCBj(M, j, im):=block([k, r], r:matrix_size(M)[1],
  for k:im thru r do if abs(M[k,j])=1 then return(kihonR(r,1,k)),
  for k:im thru r do if not M[k,j]=0 then return(kihonR(r,1,k)), return(kihonP(r,1,2,0)));

FindNZcol(M, j, s):=block([r, i], r:-1, for i:s thru matrix_size(M)[1] do if not M[i, j]=0 and r=-1 then r:i, return(r));
