const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.resolve(__dirname, '../../app/mcq-webapp/app.js'), 'utf8');
const functions = [...source.matchAll(/^function \w+\([^]*?^}/gm)].map(m => m[0]).join('\n');
const context = vm.createContext({});
vm.runInContext(functions, context);
const convert = context.legacyQuestionCasttext;
const original = String.raw`sconcat(tex2L([%_nr, "\\times", %_nc]), "行列\\(A=\\)", tex2(matAp), " を行に関して基本変形すると, ", tex2(matFq), " になる. このとき, \\(p, q\\)の値の組として正しいものを選べ.")`;
const expected = String.raw`\({@%_nr@} \times {@%_nc@}\)行列\(A=\){@matAp@} を行に関して基本変形すると, {@matFq@} になる. このとき, \(p, q\)の値の組として正しいものを選べ.`;
assert.equal(convert(original), expected);
assert.equal(convert(String.raw`sconcat("\\(A=",tex1(matAp),"\\)")`),String.raw`\(A={@matAp@}\)`);
assert.equal(convert('sconcat("a,",sconcat("b",tex2(f(x,y))),"c")'),'a,b{@f(x,y)@}c');
assert.equal(convert('sconcat("X", custom([1,2],"a,b"), "Y")'),'X{@ssubst(%__SELPROMPT, "__SELPROMPT__", ssubst(%__SELTYPE, "__SELTYPE__", sconcat(custom([1,2],"a,b"))))@}Y');
assert.match(convert('sconcat("X", tex2L(L), "Y")'),/^X\{@.*sconcat\(tex2L\(L\)\).*@}Y$/);
assert.match(convert('sconcat("X", if a then "one" else "two", "Y")'),/sconcat\(if a then "one" else "two"\)/);
assert.match(convert('sconcat("X", [1,2], "Y")'),/sconcat\(\[1,2\]\)/);
assert.equal(convert('sconcat(__SELTYPE__, " / __SELPROMPT__")'),'__SELTYPE__ / __SELPROMPT__');
assert.equal(convert(String.raw`"\\(\\begin{array}{cc}1&2\\\\3&4\\end{array}\\)"`),String.raw`\(\begin{array}{cc}1&2\\3&4\end{array}\)`);
assert.equal(convert(String.raw`sconcat("He said \"a,b\"", "\\times")`),'He said "a,b"\\times');
assert.match(convert('sconcat("a", f([1,2))'),/sconcat\(sconcat/);
assert.match(convert('sconcat("a") + sconcat("b")'),/sconcat\(sconcat/);
assert.match(convert('sconcat("outside",tex1(x))'),/sconcat\(tex1\(x\)\)/);
assert.equal(convert(String.raw`sconcat("\\[",stack_disp(a,""),"\\]")`),String.raw`\[{@a@}\]`);
if (process.env.MCQ_CASTEXT_OUTPUT) fs.writeFileSync(process.env.MCQ_CASTEXT_OUTPUT, JSON.stringify({original, converted:expected, literal:context.casttextLiteral(expected)}));
console.log('Passed: readable migration, nested calls, math context, unknown expressions, dynamic lists, prompts, escaping and malformed syntax.');
context.el={qvars:{value:fs.readFileSync(path.resolve(__dirname,'../../001/GaussElimRowReducedCheck-A.txt'),'utf8')}};
assert.equal(convert(original),expected);
context.el.qvars.value='tex2(x):=sconcat("custom",x);';
assert.match(convert('sconcat("Before",tex2(a),"After")'),/sconcat\(tex2\(a\)\)/);
console.log('Passed: conventional local wrappers and custom override preservation.');
