const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.resolve(__dirname,'../../app/mcq-webapp/app.js'),'utf8');
const functions = [...source.matchAll(/^function \w+\([^]*?^}/gm)].map(m=>m[0]).join('\n');
const field=value=>({value,closest:()=>({classList:{add(){}}})});
const el={questions:{ja:field(''),en:field('English')},questionModes:{ja:field('text')}};
const state={questionTypes:{ja:'text',en:'text'}};
const context=vm.createContext({el,state,window:{mcqNotice(){}},console});
vm.runInContext(functions+'\nfunction baseLang(){return "ja";} function markTranslationsStale(){} function updateOutput(){} function setStatus(message,error){globalThis.status={message,error};}',context);
const input=String.raw`\(a=\){@a@}のとき, \(a^2\)を求め, 次から __SELPROMPT__`;
const expected=String.raw`sconcat("\\(a=\\)", stack_disp(a, "i"), "のとき, \\(a^2\\)を求め, 次から __SELPROMPT__")`;
assert.equal(context.questionTextToCas(input),expected);
assert.equal(context.questionTextToCas(String.raw`\(a={@a@}\)`),String.raw`sconcat("\\(a=", stack_disp(a, ""), "\\)")`);
assert.equal(context.questionTextToCas(String.raw`\[{@a@}+{@b@}\]`),String.raw`sconcat("\\[", stack_disp(a, ""), "+", stack_disp(b, ""), "\\]")`);
assert.match(context.questionTextToCas('"value" {@f("@}")@} __SELTYPE__'), /stack_disp\(\(f\("@}"\)\), "i"\)/);
assert.equal(context.questionTextToCas('{@a /* @} */@}'), 'sconcat(stack_disp((a /* @} */), "i"))');
for(const bad of ['no expressions','{@a','@}','{@ @}','[[if test="true"]]{@a@}[[/if]]','{@a {@b@}']) assert.throws(()=>context.questionTextToCas(bad));
el.questions.ja.value=input;context.convertQuestionToCas();
assert.equal(el.questions.ja.value,expected);assert.equal(state.questionTypes.ja,'cas');assert.equal(el.questionModes.ja.value,'cas');assert.equal(el.questions.en.value,'English');
context.convertQuestionToCas();assert.equal(el.questions.ja.value,expected);assert.ok(context.status.error);
state.questionTypes.ja='text';el.questions.ja.value='{@bad';context.convertQuestionToCas();assert.equal(el.questions.ja.value,'{@bad');assert.equal(state.questionTypes.ja,'text');
console.log('Passed: sample, math wrappers, quoted/comment delimiters, malformed input, type change, repeated conversion and language isolation.');
if(process.env.MCQ_CONVERSION_OUTPUT) fs.writeFileSync(process.env.MCQ_CONVERSION_OUTPUT,JSON.stringify({input,converted:expected,inside:context.questionTextToCas(String.raw`\(a={@a@}\)`)}));

vm.runInContext('function activeLangs(){return ["ja","en"];} ',context);
el.questions.ja.value=input;state.questionTypes.ja='text';el.questionModes.ja.value='text';
const generated=context.langAssocFromFields();
assert.ok(generated.includes(expected));
assert.equal(el.questions.ja.value,input);
assert.equal(state.questionTypes.ja,'text');
assert.equal(el.questionModes.ja.value,'text');
assert.ok(generated.includes('["en", "English"]'));
state.questionTypes.ja='cas';el.questions.ja.value=expected;
assert.equal(context.langAssocFromFields(),generated,'Explicit and automatic conversion generate identical code');
state.questionTypes.ja='text';el.questions.ja.value='{@a';
assert.throws(()=>context.langAssocFromFields());assert.equal(el.questions.ja.value,'{@a');
console.log('Passed: automatic output conversion equals explicit conversion, preserves editor types/text, and rejects malformed input.');

context.Event=class {constructor(type,options){this.type=type;this.bubbles=options.bubbles;}};
const editor=el.questions.ja;
editor.setRangeText=function(text,start,end){this.value=this.value.slice(0,start)+text+this.value.slice(end);this.selectionStart=this.selectionEnd=start+text.length;};
editor.focus=()=>{editor.focused=true;};
editor.dispatchEvent=event=>{editor.lastEvent=event;};
editor.value='行列を 選択';editor.selectionStart=editor.selectionEnd=4;
context.insertQuestionPlaceholder('__SELTYPE__');
assert.equal(editor.value,'行列を __SELTYPE__選択');
assert.equal(editor.selectionStart,15);assert.equal(editor.selectionEnd,15);
assert.ok(editor.focused);assert.equal(editor.lastEvent.type,'input');assert.equal(editor.lastEvent.bubbles,true);
editor.value='前😀後';editor.selectionStart=1;editor.selectionEnd=3;
context.insertQuestionPlaceholder('__SELPROMPT__');assert.equal(editor.value,'前__SELPROMPT__後');
assert.equal(el.questions.en.value,'English');
editor.value='sconcat("選べ ")';editor.selectionStart=editor.selectionEnd=12;
state.questionTypes.ja='cas';context.insertQuestionPlaceholder('__SELTYPE__');
assert.equal(editor.value,'sconcat("選べ __SELTYPE__")');assert.equal(state.questionTypes.ja,'cas');
console.log('Passed: caret insertion, selection replacement, Unicode, input event, CAS literal and other-language isolation.');
